spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_system
    username: order_admin
    password: order_admin_pw

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  rabbitmq:
    host: localhost
    port: 5672
    username: order_admin
    password: order_admin_pw

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health, info
